spring:
  datasource:
    url: jdbc:postgresql://seisma.c4g3rzhrb3oy.us-east-1.rds.amazonaws.com:5432/postgres
    username: tax_calculator_user
    password: Seisma123
    driverClassName: org.postgresql.Driver
